dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server

language: rust
rust:
- stable

sudo: false

cache: cargo

env:
  global:
    - PG_HOST=localhost
    - PG_PORT=5432
    - PG_USER=postgres
    - PG_PASSWORD=
    - PG_DBNAME=deadpool
    - AMQP_ADDR=amqp://guest:guest@127.0.0.1:5672/%2f

services:
  - postgresql
  - rabbitmq
  - redis-server

before_script:
  - psql -c 'create database deadpool;' -U postgres

script:
- cargo build --workspace --verbose
- cargo test --workspace --verbose
