[package]
name = "deadpool"
version = "0.5.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool"
keywords = ["async", "database", "pool"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[dependencies]
async-trait = { version = "0.1.17", optional = true }
tokio = { version = "0.2.9", features = ["sync", "time"] }
crossbeam-queue = "0.2.0"

[dev-dependencies]
tokio = { version = "0.2.9", features = ["sync", "macros", "rt-core"] }

[workspace]
members = [
    "postgres",
    "lapin",
    "redis",
]
exclude = [
    "examples",
]

[features]
default = ["managed", "unmanaged"]
managed = ["async-trait"]
unmanaged = []
