[package]
name = "deadpool"
version = "0.1.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"
description = "Dead simple async pool"
keywords = ["database", "pool", "postgres"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
#default = ["postgres"]
postgres = ["tokio-postgres"]

[dependencies]
async-trait = "0.1.17"
futures = "0.3.1"
log = "0.4"
tokio = "0.2.0-alpha.6"
tokio-postgres = { version = "0.5.0-alpha.1", optional = true }
