[package]
name = "deadpool-lapin"
version = "0.2.0-alpha.1"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool for lapin"
keywords = ["async", "lapin", "pool", "amqp", "rabbitmq"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[dependencies]
deadpool = { path = "../", version = "0.2.3" }
async-trait = "0.1.17"
futures = "0.3.1"
log = "0.4"
lapin = { git = "https://github.com/sozu-proxy/lapin", features = ["futures"] }

[dev-dependencies]
tokio = { version = "0.2.2", features = ["macros"] }
