[package]
name = "deadpool-example-postgres-actix-web"
version = "0.1.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool-postgres = { version = "0.5.0", path = "../../postgres" }
dotenv = "0.15.0"
tokio = { version = "0.2.9", features = ["macros"] }
tokio-postgres = { version = "0.5.1" }
