[package]
name = "deadpool-example-postgres-actix-web"
version = "0.1.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.1"
config = "0.11"
deadpool-postgres = { version = "0.8", path = "../../postgres" }
dotenv = "0.15"
failure = "0.1"
serde = { version = "1", features = ["derive"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-0_8"] }
uuid = { version = "0.8", features = ["serde"] }
