[package]
name = "deadpool-example-redis-actix-web"
version = "0.1.0"
authors = ["Tomas Hromada <tomas@hey.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.1"
deadpool-redis = { version = "0.7", path = "../../redis" }
redis = { version = "0.19", features = ["tokio-comp"] }
