[package]
name = "deadpool-postgres"
version = "0.2.1"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool for tokio-postgres"
keywords = ["async", "database", "pool", "postgres"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[dependencies]
deadpool = { path = "../", version = "0.2" }
async-trait = "0.1.17"
futures = "0.3.1"
log = "0.4"
tokio = "0.2.0-alpha.6"
tokio-postgres = { version = "0.5.0-alpha.1" }
