[package]
name = "deadpool-redis"
version = "0.2.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool for redis"
keywords = ["async", "redis", "pool"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[dependencies]
deadpool = { path = "../", version = "0.2.3" }
async-trait = "0.1.17"
futures = { version = "0.3.1", features = ["compat" ] }
log = "0.4"
redis = "0.13.0"

[dev-dependencies]
tokio = { version = "0.2.2", features = ["macros"] }
